apiVersion: v1
kind: Namespace
metadata:
  name: web-apps
  labels:
    purpose: production
    security-tier: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: trusted-clients
  labels:
    purpose: testing
    security-tier: trusted
---
apiVersion: v1
kind: Namespace
metadata:
  name: database
  labels:
    purpose: database
    security-tier: internal
---
apiVersion: v1
kind: Namespace
metadata:
  name: untrusted
  labels:
    purpose: testing
    security-tier: untrusted