apiVersion: v1
kind: ServiceAccount
metadata:
  name: sbom-scanner
  namespace: sbom-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vuln-checker
  namespace: sbom-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sbom-tester
  namespace: sbom-test