# Alternative: Sealed Secrets for Git storage
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dockerhub-sealed
  namespace: private-registry-lab
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    .dockerconfigjson: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEqIfY5r4RqUExF0HCMmCPFp5A2nqQ...
  template:
    metadata:
      name: dockerhub-regcred
      namespace: private-registry-lab
    type: kubernetes.io/dockerconfigjson