apiVersion: v1
kind: ServiceAccount
metadata:
  name: falco-installer
  namespace: falco-system
  annotations:
    "helm.sh/hook": pre-install
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: falco-tester
  namespace: falco-test